name: My Workflow

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run script 1
        run: |
          echo "This is job 1"
          sleep 10

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run script 2
        run: |
          echo "This is job 2"
          sleep 5

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run script 3
        run: |
          echo "This is job 3"
          sleep 15

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run script 4
        run: |
          echo "This is job 4"
          sleep 20
