name: 🗃️ Automated Project

on:
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, edited, synchronize, closed]
  workflow_dispatch:
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Everything to Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: 'https://github.com/users/offensive-vk/projects/<project-number>'
          github-token: ${{ secrets.BOT_TOKEN }}